### ISSUE TITLE
Obligations date range is hard coded to 2018

### ISSUE THREAD

**Issue by MJCallahanPage** [hmrc/vat-summary-frontend#322]
The date range for retrieving obligations is hard coded to 1-1-2018 to 31-1-2018.

This needs to be fixed before the turn of the year. It's a similar to issue to one on view-vat-returns-frontend.

https://github.com/hmrc/vat-summary-frontend/blob/master/app/services/VatDetailsService.scala#L38-L50

**Comment by lewishayqa** [comment]
There is a Jira task on the backlog regarding this that was raised a long time ago (BTAT-2742). Unfortunately because of other work taking priority (as this will not be a problem until 2019), we have not been able to address this since it was raised.

The existing Jira story could be used to track the work in the future (the description/title of it may need to be updated to cover all occurrences of the issue).

**Comment by miranda-hawkes** [comment]
Addressed and fixed by: https://github.com/hmrc/vat-summary-frontend/pull/347
